### ISSUE TITLE
Compiling broken on Ubuntu Jammy with Varnish 7.2.1

### ISSUE THREAD

**Issue by scyrma** [gquintard/vmod_reqwest#4]
Hi, 

Upgrading infrastructure to Ubuntu 22.04, which comes with Varnish 6.6, could not use vmod_curl anymore, so upgraded to Varnish 7.2.1 (earlier versions not being easily available for Ubuntu 22.04/Jammy).  I saw [a message about vmod_reqwest](https://github.com/varnish/libvmod-curl/issues/54#issuecomment-1151078871), and while I understand this project does not advertise compatibility with that version of Varnish, I thought I'd give it a try.

So, compiling seems to work well, but breaks at "Compiling varnish v0.0.10", with the following errors:

```bash
error[E0609]: no field `handling` on type `&&mut vrt_ctx`
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/varnish-0.0.10/src/vcl/ctx.rs:107:19
    |
107 |             if *p.handling == VCL_RET_FAIL {
    |                   ^^^^^^^^ unknown field
    |
    = note: available fields are: `magic`, `syntax`, `vclver`, `method`, `vpi` ... and 15 others

error[E0609]: no field `handling` on type `&&mut vrt_ctx`
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/varnish-0.0.10/src/vcl/ctx.rs:110:24
    |
110 |             assert!(*p.handling == 0);
    |                        ^^^^^^^^ unknown field
    |
    = note: available fields are: `magic`, `syntax`, `vclver`, `method`, `vpi` ... and 15 others

error[E0609]: no field `handling` on type `&&mut vrt_ctx`
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/varnish-0.0.10/src/vcl/ctx.rs:111:16
    |
111 |             *p.handling = VCL_RET_FAIL;
    |                ^^^^^^^^ unknown field
    |
    = note: available fields are: `magic`, `syntax`, `vclver`, `method`, `vpi` ... and 15 others

error[E0560]: struct `vrt_ctx` has no field named `handling`
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/varnish-0.0.10/src/vcl/ctx.rs:196:17
    |
196 |                 handling: ptr::null::<c_uint>() as *mut c_uint,
    |                 ^^^^^^^^ `vrt_ctx` does not have this field
    |
    = note: available fields are: `magic`, `syntax`, `vclver`, `method`, `vpi` ... and 15 others
```

I am sadly not versed in Rust and could not find where to start figuring out what could be done.

**Comment by gquintard** [comment]
Hi @scyrma,

Indeed, the API changed somewhat and broke compatibility and while `varnish-rs` (the actual vmod glue) got updated, i haven't had the time to update the various vmods relying on it.

I will do so some time this week, but the good news is that if you look at the `Cargo.toml` file and update all the `varnish-sys` and `varnish-rs` line (all 4 of them) from `0.0.10` to `0.0.12`, it should work. If it doesn't, I'll have a look urgently

**Comment by scyrma** [comment]
Indeed, it does! I was not expecting such a fast answer, thanks! (Merci!)

```
$ cargo build --release
    Updating crates.io index
  Downloaded varnish v0.0.12
  Downloaded varnish-sys v0.0.12
  Downloaded 2 crates (59.3 KB) in 0.12s
   Compiling varnish-sys v0.0.12
   Compiling reqwest v0.11.8
   Compiling varnish v0.0.12
   Compiling vmod_reqwest v0.0.4 (/root/src/vmod_reqwest)
    Finished release [optimized] target(s) in 52.55s
```

...and on to the interesting part of using it in the vcl file!

**Comment by gquintard** [comment]
Merci à toi de l'avoir signaler surtout!

I've actually took the time to release `v.0.0.5` that targets `varnish 7.2` and CI looks happy, so you can just use head of the `main` branch again.

Please note that we have a [varnish discord server](https://discord.gg/EuwdvbZR6d) if you need any help in a more synchronous manner.
