### ISSUE TITLE
Dockerfile is still of ver 0.0.6

### ISSUE THREAD

**Issue by rr923** [gquintard/vmod_reqwest#7]
Could you please get it updated to ver 0.0.9? Thanks

**Comment by gquintard** [comment]
yes, that's the plan for the near future, I just have a bunch of other packages and other vmods to update before that. Would you mind offering a PR by any chance?

**Comment by rr923** [comment]
I'd like to, let me try.

**Comment by gquintard** [comment]
thanks! it should just be a matter of changing the vmod version and the `varnish72` in the URL

**Comment by rr923** [comment]
PR created, sorry for the delay.

**Comment by rr923** [comment]
We have this error:
```
varnish         | Message:
varnish         |       Loading vmod reqwest from ./vmod_cache/_vmod_reqwest.d09390707cc59918b860b020338a91addbc28eab57d677516b2a0c6d180fa289 (/usr/lib/varnish/vmods/libvmod_reqwest.so):
varnish         | dlopen() failed: libssl.so.1.1: cannot open shared object file: No such file or directory
```

**Comment by rr923** [comment]
And looks like libssl cannot work well with debian:bookworm-slim, on which varnish 7.4 is based. Any ideas?

**Comment by gquintard** [comment]
thanks, #8 has been merged. And I can run the container, can you see if the top of `main` works for you?
